source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
target 'DeferScreenEdgeSystemGesturesTest' do
use_frameworks!

post_install do |installer|
  puts 'Setting appropriate code signing identities'
  codesign_rn_pods = true
  targetsToFix = ["EXConstants-EXConstants", "EXUpdates-EXUpdates", "React-Core-AccessibilityResources", "expo-dev-launcher-EXDevLauncher", "expo-dev-menu-EXDevMenu"]

  # Get main project development team id, or fetch from env var: dev_team = ENV['XCODE_DEVELOPMENT_TEAM']
  dev_team = ""
  project = installer.aggregate_targets[0].user_project
  project.targets.each do |target|
    target.build_configurations.each do |config|
      if dev_team.empty? and !config.build_settings['DEVELOPMENT_TEAM'].nil?
        dev_team = config.build_settings['DEVELOPMENT_TEAM']
      end
    end
  end

  installer.pods_project.targets.each do |target|
    target_is_resource_bundle = target.respond_to?(:product_type) && target.product_type == 'com.apple.product-type.bundle'
    target.build_configurations.each do |config|
      # Bitcode is not needed for now, XCode 14.1.0+
      # config.build_settings['ENABLE_BITCODE'] = 'YES'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] =  '10.0'

      if targetsToFix.include?(target.name) || target_is_resource_bundle
        puts "Set development team for target #{target.name}, isBundle: #{target_is_resource_bundle}, dev_team: #{dev_team}"
        config.build_settings['DEVELOPMENT_TEAM'] = dev_team
        if codesign_rn_pods
          if config.name.include?('Release')
            puts " .. Setting codesign identity to distribution for target #{target.name}"
            config.build_settings["CODE_SIGN_IDENTITY"] = "Apple Distribution";
            config.build_settings["CODE_SIGN_STYLE"] = "Manual";
          end
        else
          puts " .. Removing code signing for target #{target.name}"
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
          config.build_settings['CODE_SIGNING_IDENTITY'] = '-'
          config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = '-'
        end
      end
    end
  end
end
end
